FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN pip install --no-cache-dir -e . && pip install --no-cache-dir -r webapi/requirements.txt
EXPOSE 8000
CMD ["uvicorn", "webapi.app:app", "--host", "0.0.0.0", "--port", "8000"]
